### ISSUE TITLE
Exchange rate of some banks doesn't up to date

### ISSUE THREAD

**Issue by Biloleg** [dontgiveafish/hryvna-today#33]
Exchange rate of Ukrexim, OTP, Idea and Pumb banks on hryvna.today don't updates and shows old rate.

**Comment by abagayev** [comment]
Thanks for patience! Everything is fixed now.

**Comment by Biloleg** [comment]
Idea bank still shows an old data

**Comment by abagayev** [comment]
It will be updated the next time page will be regenerated.
