### ISSUE TITLE
24.03.2020 Bank Credit Dnipro wrong exchange rate

### ISSUE THREAD

**Issue by euglv** [dontgiveafish/hryvna-today#34]
![image](https://user-images.githubusercontent.com/5290141/77417914-cab87c00-6dce-11ea-823b-2e07e2089a60.png)

**Comment by abagayev** [comment]
thanks for posting this, but looks like it's on their page, looking for them to fix it
https://creditdnepr.com.ua/currency

![image](https://user-images.githubusercontent.com/11406794/77420406-a52d7180-6dd2-11ea-98de-c3c5f25b7786.png)

**Comment by Thealoner** [comment]
Я написал им в саппорт.
Может быть имеет смысл курсы со значительным (в разы) отклонением от среднего отфильтровывать при подсчете среднего курса? Обидно, что такой вот "Rogue Bank" так сильно влияет на работу сервиса.

**Comment by abagayev** [comment]
тоже писал, без реакции, но сегодня курсы обновили

true, это стоит добавить, сделаю как будет время :-)
