### ISSUE TITLE
Incorrect exchange rate in email

### ISSUE THREAD

**Issue by vladholubiev** [dontgiveafish/hryvna-today#9]
| Rate in a daily email | Rate on the website |
| --- | --- |
| ![image](https://cloud.githubusercontent.com/assets/3817380/12449552/cebf8924-bf86-11e5-9ad4-416295815303.png) | ![image](https://cloud.githubusercontent.com/assets/3817380/12449567/dfcb4d52-bf86-11e5-8dda-8eb66ed34d0f.png) |

For the first time this bug was introduced on the January 18th.

**Comment by abagayev** [comment]
Fixed! Many thanks.

**Comment by vladholubiev** [comment]
@abagayev wow, lightning fast fix, thank you too.
